### ISSUE TITLE
Major code reorganization among repositories

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/questions-and-answers#2]
For starters, I'd elaborate a list of all the functional libraries (these will mostly be yarp devices) that are of use, and functional programs. Once we lay the tree out, it will be easier to see what goes where. This could take some time!

**Comment by jgvictores** [comment]
Started project: https://github.com/orgs/roboticslab-uc3m/projects/2

**Comment by jgvictores** [comment]
Here some notes regarding what @PeterBowman and me have been  commenting.

## Common (OK)
- QA
- best-practices
- installation-guides
- openrave-yarp-plugins
- project-generator

## Common (:truck:)
- (migrate sf to gh) travislib
- teo-body (plugins:canBus,jr3)
- teo-head (programs:haar,color,asr)(plugin: tts(#38))
- asibot-main (https://github.com/roboticslab-uc3m/asibot-main/issues/21, https://github.com/roboticslab-uc3m/asibot-main/issues/28)
- teo-main (https://github.com/roboticslab-uc3m/teo-main/issues/74)

## Research (OK)
- textiles
- xgnitive

## TEO
- teo-openrave-models
- (must create) asibot-openrave-models
- follow-me

## Event (OK)
- workshop-humanoids2016

## Dont-touch
- manip-waiter (contains duplicates)(@jmgarciah)
- waiter (@jmgarciah)
- fusion-control (@jmgarciah)
- gait (@munozyanez)
- gaitcontrol (@munozyanez)
- TEO_push (TFM @j-lorente)
- teo_batc (TFM @RaulFdzbis)
- teo-ros-simulation (TFM @RaulFdzbis)
- teo-gazebo (TFM @RaulFdzbis)
- force-torque-balance (TFM @lpinel)
- teo_robot (TFM @RaulFdzbis)
- teotragen_com (@domingoesteban)
- TEOTraGen (@domingoesteban / @munozyanez)

## Forks
- open_abb (used for textiles/unfolding-industrial)
- LoliRepo (TFM @lpinel) (contains jr3 program, serves as base for teo-body jr3 plugin)

**Comment by jgvictores** [comment]
![imag1439 2](https://cloud.githubusercontent.com/assets/4448588/22844250/90074162-efdd-11e6-83db-b9bcd6e4bec7.jpg)

**Comment by David-Estevez** [comment]
OK means that I passed the exam? :sweat_smile:

**Comment by jgvictores** [comment]
@David-Estevez LOL :smile:

**Comment by jgvictores** [comment]
![imag1452](https://cloud.githubusercontent.com/assets/4448588/23080033/9ccab664-f54f-11e6-817e-d75d0bde1e28.jpg)

**Comment by jgvictores** [comment]
Regarding TEO, documenting current state here: https://github.com/roboticslab-uc3m/teo-software-manual/blob/master/README.md

Another important discussion on all this is: https://github.com/roboticslab-uc3m/QA/issues/15 I've added to https://github.com/orgs/roboticslab-uc3m/projects/2

**Comment by PeterBowman** [comment]
Most of this is already done (not exactly as we planned at first, though), we are tracking remaining work at https://github.com/orgs/roboticslab-uc3m/projects/2.

**Comment by jgvictores** [comment]
Ok, closing issue and tracking remaining work at https://github.com/orgs/roboticslab-uc3m/projects/2 !!
