### ISSUE TITLE
Move or rename yarp plugins directories?

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/questions-and-answers#23]
As spoken with @David-Estevez the current names (`TeoYarp`, etc) are misleading. Options:
1. Rename.
1. Move contents up one level.

Opinions?

**Comment by David-Estevez** [comment]
Just to clarify, I was talking about the [yarp-devices repo](https://github.com/roboticslab-uc3m/yarp-devices). In case there are differences between the code in this folder and the code in the same-level, I find correct to place all the sources for the plugins in a folder to distinguish them from the rest of the code. But, instead of naming this folder TeoYarp, as it is no longer related to Teo, I would call the folder `yarp-devices' (or another descriptive name). 

If all the plugins are similar,  I think it is ok to put them on the same level.

**Comment by jgvictores** [comment]
Correct. Also clarifying, this happens among several repositories, that contain a YARP plugins folder which was not correctly renamed during [the great transition](https://github.com/roboticslab-uc3m/QA/issues/2). For instance:
- [ ] https://github.com/roboticslab-uc3m/yarp-devices/tree/develop/libraries/BodyYarp
- [ ] https://github.com/roboticslab-uc3m/kinematics-dynamics/tree/develop/libraries/TeoYarp
- [ ] https://github.com/roboticslab-uc3m/vision/tree/develop/libraries/VisionYarp (maybe this last one is not as bad)

**Comment by PeterBowman** [comment]
I'd pick a catchy name and use it consistently across all repos. Somebody took a step ahead a while ago and created a [`yarpplugins`](https://github.com/roboticslab-uc3m/openrave-yarp-plugins/tree/67e2c2d/yarpplugins) directory at openrave-yarp-plugins. On the other hand, YARP itself distinguishes between carriers and devices, placing them in their own folder: [yarp/src/{carriers+devices}](https://github.com/robotology/yarp/tree/9b32448/src).

**Comment by rsantos88** [comment]
https://github.com/roboticslab-uc3m/yarp-devices/tree/develop/libraries/BodyYarp -> (done it [here](https://github.com/roboticslab-uc3m/yarp-devices/pull/130))
https://github.com/roboticslab-uc3m/kinematics-dynamics/tree/develop/libraries/TeoYarp -> (done it [here](https://github.com/roboticslab-uc3m/kinematics-dynamics/pull/125))
https://github.com/roboticslab-uc3m/vision/tree/develop/libraries/VisionYarp (done it [here](https://github.com/roboticslab-uc3m/vision/pull/71))

**Comment by jgvictores** [comment]
- [ ] https://github.com/roboticslab-uc3m/tools

**Comment by rsantos88** [comment]
>  https://github.com/roboticslab-uc3m/tools

done it [here](https://github.com/roboticslab-uc3m/tools/pull/8)!!

**Comment by rsantos88** [comment]
@jgvictores if you think that all of the changes are correct and there is nothing more to change, please close this issue :)

**Comment by jgvictores** [comment]
Yes, I also did this on [openrave-yarp-plugins](https://github.com/roboticslab-uc3m/openrave-yarp-plugins/tree/f6d6c3e039771fc4c5fe4985f0a502ea34c43e32/libraries), so I think we're good to go.

@rsantos88 Thanks!

**Comment by jgvictores** [comment]
> On the other hand, YARP itself distinguishes between carriers and devices, placing them in their own folder: [yarp/src/{carriers+devices}](https://github.com/robotology/yarp/tree/9b32448/src).

Regarding this, I think we're okay to go for now, no existing carriers, no short-term plans, no long-term plans of creating many.
