### ISSUE TITLE
Rename this repo?

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/questions-and-answers#32]
Something among the lines of the following should increase visibility:
- questions-answers
- questions-and-answers

Opinions?

**Comment by PeterBowman** [comment]
I'm not opposing, but isn't this visible enough?

![qa](https://user-images.githubusercontent.com/9977198/31307233-e77b1b9c-ab5f-11e7-8ded-00cdeed29416.png)

**Comment by jgvictores** [comment]
IMHO, initials can always be misleading, especially to non-native speakers. I couldn't find this in our current best-practices, but at least it was in the Google code style last time I checked. :-)

**Comment by PeterBowman** [comment]
:+1: The good thing is, we can keep the redirect from the shorter name (I bet that people don't like to type too much). I'd choose `questions-and-answers` as its more clear to me.

**Comment by jgvictores** [comment]
Thanks! Done!
