### ISSUE TITLE
A couple of problems related to Teo movements

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/questions-and-answers#34]
There are a couple of problems related to Teo movements and it can ruin a demonstration (leading to reset it several times... :sweat:)
* The first occurs randomly, when the program sends  a sequence of movements, for example salute, composed by four movements: lift arm up, axial arm turn in, axial arm turn out, move arm down.
We can see that this movement is not executed correctly in certain occasions. The arm finishes the movements early, running all at once and not sequentially. This can produce a freeze of all the demo, because the movement has not finished correctly all the sequence. Can it be a problem with checkCanBus() function? Why does it works well sometime and sometimes not?
* Other problem observed is, when Teo makes a movement (I would highlight **axial movements**), sometimes is not finished and the joint starts to shake (like a parkinson). This may take a while (shaking horribly) until the movement finally ends.

I don't know where I can post this problems, because the first can be a software problem, but the second it can be a tunning motors problem ¿? I don't know
I need some ideas to solve it.

**Comment by jgvictores** [comment]
This issue was moved to roboticslab-uc3m/teo-main#22
