### ISSUE TITLE
Improve CONTRIBUTING.md

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/questions-and-answers#5]
Sample: https://github.com/roboticslab-uc3m/teo-main/blob/develop/CONTRIBUTING.md

**Comment by jgvictores** [comment]
Also look at: http://discourse.ros.org/faq

**Comment by jgvictores** [comment]
And: http://wiki.ros.org/Support

**Comment by David-Estevez** [comment]
Those ROS guides look really nice...

**Comment by jgvictores** [comment]
Yet another good reference: https://github.com/blog/2267-introducing-github-community-guidelines

**Comment by jgvictores** [comment]
Added at 47a8cc6c26080608da6fca938e0ffbf41b469795, but must improve.

**Comment by jgvictores** [comment]
Yet another reference: http://wiki.ros.org/action/info/BestPractices

**Comment by PeterBowman** [comment]
> Yet another good reference: https://github.com/blog/2267-introducing-github-community-guidelines

GitHb has made available a handy wizard at Insights > Community to choose and upload a code of conduct statement.

**Comment by PeterBowman** [comment]
> Sample: https://github.com/roboticslab-uc3m/teo-main/blob/develop/CONTRIBUTING.md

I believe all our CONTRIBUTING.md files have been synchronized with that one. Moreover, when this file is missing in a specific repo, the global one is pulled from [roboticslab-uc3m/.github](https://github.com/roboticslab-uc3m/.github/blob/9cb9df19a6acfbaa7f8fc042d76e3ab07eb80118/CONTRIBUTING.md). @jgvictores what next?

**Comment by jgvictores** [comment]
IMHO:
1) Update (not mandatory, forget it too tedious): http://robots.uc3m.es/index.php/TEO -> https://apps.robots.uc3m.es/index.php/TEO (I'll open an issue regarding the validness of the certificate)
2) Close this issue ^^

**Comment by PeterBowman** [comment]
OK, but I'd rather forget about the wiki altogether and only recommend a GitHub search. I believe the most relevant stuff has been already migrated (?).

PS certain links stopped working after you deleted the redirections I had prepared at https://github.com/roboticslab-uc3m/questions-and-answers/issues/91#issuecomment-805120205. For instance, see [TEO Cluster: Network, IP, MAC and PC specification list](http://robots.uc3m.es/gitbook-teo-developer-manual/network-information.html). The wiki is archived, hence no one can edit and fix that link.

**Comment by jgvictores** [comment]
> OK, but I'd rather forget about the wiki altogether and only recommend a GitHub search. I believe the most relevant stuff has been already migrated (?).

Perfect!

> PS certain links stopped working after you deleted the redirections I had prepared at #91 (comment).

Sorry about that again! 

> For instance, see TEO Cluster: Network, IP, MAC and PC specification list. The wiki is archived, therefore no one can edit and fix that link.

Oh, that was https://github.com/roboticslab-uc3m/teo-developer-manual/issues/19 anyway ^^ Some day we'll find a decent mechanism for that.

**Comment by PeterBowman** [comment]
Done as part of https://github.com/roboticslab-uc3m/questions-and-answers/issues/93#issuecomment-1001805412.

As a side note, whenever a repo lacks CONTRIBUTING.md, it is automatically pulled from https://github.com/roboticslab-uc3m/.github/. Also, it is possible to show the contents of a README.md file added there on the org's main page (https://github.com/roboticslab-uc3m).
