### ISSUE TITLE
Think about AppVeyor (Windows + Linux CI)

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/questions-and-answers#51]
AppVeyor goes Linux according to https://www.appveyor.com/blog/2018/03/06/appveyor-for-linux/.

See how it works in [asrob-uc3m/robotDevastation](https://github.com/asrob-uc3m/robotDevastation):

* [YAML file](https://github.com/asrob-uc3m/robotDevastation/blob/57f65643dcf618ffaba81d6299b89dde698e40e0/.appveyor.yml)
* https://ci.appveyor.com/project/asrob-uc3m/robotdevastation

Also: [YARP's .appveyor.yml](https://github.com/robotology/yarp/blob/b0b7f5f028dcdcf4e8e23397e1b22d759081064e/.appveyor.yml).

**Comment by jgvictores** [comment]
Looks good, but we should measure where we put our efforts, as at least we have Travis CI.

**Comment by PeterBowman** [comment]
In case anyone would like to fiddle with this, here is the follow-up from the AppVeyor blog: https://www.appveyor.com/blog/2018/05/15/appveyor-for-linux-is-generally-available/.

**Comment by PeterBowman** [comment]
Funnily, Travis also supports Windows builds, now: https://blog.travis-ci.com/2018-10-11-windows-early-release.

**Comment by PeterBowman** [comment]
> Funnily, Travis also supports Windows builds, now: https://blog.travis-ci.com/2018-10-11-windows-early-release.

Tested in https://github.com/roboticslab-uc3m/color-debug/pull/18. Honestly, I don't want to think about AppVeyor anymore. In case we ever need to test our code against Windows, let's try Travis first. If there is any compelling reason (e.g. missing dependencies?), switch to AppVeyor, which in my experience is quite tedious to work with (you need to learn the CMD/PowerShell syntax, no parallel jobs).

**Comment by jgvictores** [comment]
Totally agreed. Given the situation with Travis supporting Windows and the extra cons you mention, AppVeyor does not seem the way to go right now.
