### ISSUE TITLE
Migration to travis-ci.com

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/questions-and-answers#60]
* https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps
* https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#Existing-Open-Source-Repositories-on-travis-ci.org

**Comment by PeterBowman** [comment]
BTW there is a new *Checks* tab in every pull request. Per https://blog.github.com/2018-05-07-introducing-checks-api/:

> As a leading provider of hosted CI, Travis CI has been helping build and test open source and private projects for more than seven years. Travis CI recently adopted GitHub Apps and now includes Checks as a way for your team to share the results of your project’s branch and pull request builds. View your build’s stages, jobs, and results, including the config associated with them to get a complete picture of the health of your projects directly from GitHub. You can also rerun builds from within the GitHub Checks UI.

https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com

**Comment by PeterBowman** [comment]
https://blog.travis-ci.com/2018-09-27-deprecating-github-commit-status-api-for-github-apps-managed-repositories

**Comment by jgvictores** [comment]
AFAIK I've authorized the new GitHub App everywhere.

**Comment by PeterBowman** [comment]
I just did it on asrob-uc3m, we have to wait until the request is processed by Travis staff.

**Comment by PeterBowman** [comment]
> I just did it on asrob-uc3m, we have to wait until the request is processed by Travis staff.

I noticed today that all asrob-uc3m repos (even those that don't use CI) show up on travis-ci.com: https://travis-ci.com/asrob-uc3m ([config page](https://travis-ci.com/organizations/asrob-uc3m/repositories)). However, the only three repos we configured CI on are still disabled:

> The following repositories cannot be migrated to travis-ci.com at this time because they are currently active on our legacy platform travis-ci.org. This feature will be available shortly. Please [read our docs on open source migration](https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#existing-open-source-repositories-on-travis-ciorg) to learn more.

**Comment by PeterBowman** [comment]
> BTW there is a new _Checks_ tab in every pull request.

Tested in https://github.com/roboticslab-uc3m/color-debug/pull/18, see [*Checks*](https://github.com/roboticslab-uc3m/color-debug/pull/18/checks).

**Comment by PeterBowman** [comment]
Now an opt-in feature for beta-testers: https://docs.travis-ci.com/user/migrate/open-source-repository-migration.

**Comment by PeterBowman** [comment]
Done for all three robotDevastation-related repos on asrob-uc3m! Had to enable GitHub apps in the orgs' settings page, then log in to old travis-ci.org, check settings and "Sign up for the beta" (left panel). On the next day, I was able to see a "Migrate" tab on the asrob-uc3m settings screen in travis-ci.com. Migration thereafter only took a few seconds.

**Comment by PeterBowman** [comment]
All roboticslab-uc3m repos have been migrated to travis-ci.com, too. Except teo-bimanipulation, which seems to run on both servers at once, not sure why. Old build history will be migrated in the following months.

**Comment by PeterBowman** [comment]
Sweeeet: https://github.com/roboticslab-uc3m/yarp-devices/runs/185402469.
