### ISSUE TITLE
Avoid hardcoded absolute paths in .ini files

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/questions-and-answers#61]
Following the lines of #52, I'd be tempted to mimick the CMake `configure_file` mechanism in several absolute paths found throughout out &lt;robot&gt;-configuration-files repos. [Example](https://github.com/roboticslab-uc3m/teo-configuration-files/blob/b37b041ddcfddfe1347cfb4d5c22737d0aa069d2/share/teoSimBase/scripts/teoSimBase.xml#L9-L13):

```ini
<module>
        <name>yarpdev</name>
        <parameters>--device BasicCartesianControl --name /teoSim/rightArm/CartesianControl --from /usr/local/share/teo-configuration-files/contexts/kinematics/rightArmKinematics.ini --angleRepr axisAngle --robot remote_controlboard --local /BasicCartesianControl/teoSim/rightArm --remote /teoSim/rightArm</parameters>
        <node>localhost</node>
</module>
```

Note the `/usr/local/share/...` part. Since moving everything into a `cmake/templates/` in the form of a `*.xml.in` would mess the directory structure of the affected repositories, YARP context paths might come into play as a better approach, e.g. `... --context teo-kinematics --from rightArmKinematics.ini`. Keep in mind that context names should be **unique**, hence the `teo-` prefix.

**Comment by jgvictores** [comment]
> YARP context paths might come into play as a better approach

Yes, that looks elegant.

> Keep in mind that context names should be unique, hence the teo- prefix.

:+1:

**Comment by jgvictores** [comment]
Mmm thinking again, anything really wrong with non-unique `kinematics`?

**Comment by jgvictores** [comment]
>  I thought that unique context names may be preferable over unique .ini file names in terms of readability (only one prefix in the directory name instead of prefixing every file).

Ok, makes perfect sense!

**Comment by PeterBowman** [comment]
There is also another option to `yarp-config`: `robot`. That is, call `yarp-config robot --import amor` prior to working with AMOR and so on. Not sure about potential caveats, though, I've never used this.

**Comment by PeterBowman** [comment]
To sum up: prefix context file names with the robot name (e.g. `teo-`). Thus, the following ([ref](https://github.com/roboticslab-uc3m/teo-configuration-files/blob/a741cd12a38a1d9e83a03743bedfcf004d748133/share/applications/teoBase.xml#L68-L73)):

```xml
<module>
  <name>BasicCartesianControl</name>
  <parameters>--from /usr/local/share/teo-configuration-files/contexts/kinematics/fixedTrunk-leftArm-fetch-kinematics.ini ...</parameters>
  <node>localhost</node>
  <deployer>yarpdev</deployer>
</module>
```

would become:

```xml
<module>
  <name>BasicCartesianControl</name>
  <parameters>--from teo-fixedTrunk-leftArm-fetch-kinematics.ini ...</parameters>
  <node>localhost</node>
  <deployer>yarpdev</deployer>
</module>
```

This is entirely dependent on the implementation of each module. Here, *BasicCartesianControl* should either parse `--context kinematics` or perform file look-up on this default path (preferable); also, additional mechanisms exist, i.e. this device accepts the `--kinematics` option, which we rarely use.

@jgvictores do you agree?

**Comment by jgvictores** [comment]
I think so. Maybe we could close this issue because too broad then?
1. Update http://robots.uc3m.es/gitbook-developer-manual/programming-with-yarp.html ([perma](https://github.com/roboticslab-uc3m/developer-manual/blob/b75a4e45a312fab2857f633e7b4c7403432613cc/programming-with-yarp.md)) to make more emphasis on using YARP mechanisms for resources (installation, finding).
2. Check all CMake resource installations and all YARP module finding. <-- way too tedious

**Comment by PeterBowman** [comment]
> Check all CMake resource installations and all YARP module finding. <-- way too tedious

I think it's not that hard at all, the only occurrence of hardcoded paths I could find in teo-config-files is the bcc-kinematics thing. Same goes for amor-/asibot-config-files, probably.

**Comment by PeterBowman** [comment]
BTW we got rid of long absolute paths pointing at OpenRAVE environment descriptor files at https://github.com/roboticslab-uc3m/openrave-yarp-plugins/issues/99.

**Comment by PeterBowman** [comment]
> To sum up: prefix context file names with the robot name (e.g. `teo-`).

I didn't notice my original proposal was to rename **contexts** instead of individual **files**. However, now I realize modules can hardcode this context name behind the scenes ([ref](https://github.com/roboticslab-uc3m/kinematics-dynamics/blob/a9068fbc4ddb3b9bb73b024cdacf875e456292f8/libraries/YarpPlugins/KdlSolver/DeviceDriverImpl.cpp#L142)). It kinda makes sense doing so since:

* Callers (anyone invoking this module) avoids passing an extra `--kinematics-context` option.
* Devs are told to install robot-specific kinematics in a common context name, no ambiguities allowed.

@jgvictores OK with https://github.com/roboticslab-uc3m/teo-configuration-files/commit/a89480fa727433826e875cd606c843586cacb4a7?

**Comment by jgvictores** [comment]
> @jgvictores OK with [roboticslab-uc3m/teo-configuration-files@a89480f](https://github.com/roboticslab-uc3m/teo-configuration-files/commit/a89480fa727433826e875cd606c843586cacb4a7)?

That's perfect, thanks a lot!

**Comment by PeterBowman** [comment]
Done, now we point at filenames instead of full paths (see linked commits).
