### ISSUE TITLE
New Xenial images available on Travis CI

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/questions-and-answers#73]
*Ubuntu Xenial 16.04 build environment is here!* (https://changelog.travis-ci.com/ubuntu-xenial-16-04-build-environment-is-here!-79690)

Full docs: https://docs.travis-ci.com/user/reference/xenial:

* CMake 3.12.4
* GCC 5.4.0
* Python 2.7.15, 3.6.5 and 3.7.1

**Comment by PeterBowman** [comment]
I just gave it a try in https://travis-ci.com/roboticslab-uc3m/color-debug/jobs/161080835.

**Comment by jgvictores** [comment]
- Developer PCs: Per the current state of https://github.com/roboticslab-uc3m/developer-manual/blob/bcc0c12459da5b07ee274c32081401fd3a34b8df/main-developer-tools.md#main-developer-tools we recommend Ubuntu `16.04` and `18.04`.
- TEO: Ubuntu 14.04 per https://github.com/roboticslab-uc3m/teo-main/issues/32
- ASIBOT: Per https://github.com/roboticslab-uc3m/questions-and-answers/issues/20#issuecomment-437351862 has headless Debian Jessie (aka Debian 8).

Maybe Trusty makes sense for repos such as `yarp-devices` and `kinematic-dynamics`?

**Comment by PeterBowman** [comment]
>     * TEO: Ubuntu 14.04

Actually, it's Ubuntu 16.04 ATOW (https://github.com/roboticslab-uc3m/teo-developer-manual/issues/42#issuecomment-442238739).

> Maybe Trusty makes sense for repos such as `yarp-devices` and `kinematic-dynamics`?

Not so long ago we had a similar debate about Precise vs Trusty: https://github.com/roboticslab-uc3m/yarp-devices/issues/111. My main concern was expressed in https://github.com/roboticslab-uc3m/yarp-devices/issues/111#issuecomment-351041371 - this is a somehow distro-agnostic train of thought that concerns: 1) the dependencies we expect users to install along our software; 2) the build environment available in Trusty images. Note that Trusty on Travis provides CMake 3.9.x, well ahead the v3.5 release we assume everybody will use if ever talking about Ubuntu 14.04. Therefore, there is an asymmetry between these two environments that we can't avoid - just adapt to it and keep in mind any potential pitfalls (e.g. the Travis build succeeds but my local machine doesn't).

My 0.05€: follow the updates in Travis & Xenial images, wait until this environment is considered stable enough (should be already), make sure no conflicts arise with regard to our code (shouldn't, everything is well tested and documented on this SO), migrate **all** Trusty builds to Xenial gradually. Keep in mind Trusty's EOL!

**Comment by jgvictores** [comment]
Okay! Updated the info regarding TEO's OSs. Totally agree with your 0.05€ !!! :smile:

**Comment by PeterBowman** [comment]
I'd consider moving to YARP 3.0 (https://github.com/roboticslab-uc3m/questions-and-answers/issues/65) shortly afterwards. BTW (https://github.com/roboticslab-uc3m/questions-and-answers/issues/65#issuecomment-397658934):

> ASWJ, in the future, we'd like to create one tag per repo prior to requiring YARP 3.0 everywhere. The goal is to keep track of the last point in the commit history that supported YARP 2.x.

**Comment by PeterBowman** [comment]
Xenial is going to become the default Linux build environment, starting next week: https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment.

> My 0.05€: follow the updates in Travis & Xenial images, wait until this environment is considered stable enough (should be already), make sure no conflicts arise with regard to our code (shouldn't, everything is well tested and documented on this SO), migrate **all** Trusty builds to Xenial gradually. Keep in mind Trusty's EOL!

I'll be working on it, [triggered builds](https://docs.travis-ci.com/user/triggering-builds) may come in handy here.

**Comment by PeterBowman** [comment]
Issues:

* [roboticslab-uc3m/xgnitive](https://travis-ci.org/roboticslab-uc3m/xgnitive/builds/522199183): no PPA available for PCL libraries on Xenial, try `libpcl-dev` apt package instead ([install guide](https://github.com/roboticslab-uc3m/installation-guides/blob/48895b99220ee33b85b85cad8db0f50b091108b1/install-pcl.md#install-pcl-172-14build1-with-vtk-620dfsg1-10build1-ubuntu-1604))

* [asrob-uc3m/yarp-devices](https://travis-ci.org/asrob-uc3m/yarp-devices/builds/522200286): `libserial-dev` should depend on `libboost-dev` since Xenial, a bug report was sent ([ref](https://bugs.launchpad.net/ubuntu/+source/libserial/+bug/1825551))

* [asrob-uc3m/robotDevastation](https://travis-ci.org/asrob-uc3m/robotDevastation/builds/522200480): `Can't open /etc/init.d/xvfb`, see *3. Headless browser testing* in [this blog entry](https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment#3-headless-browser-testing)

**Comment by PeterBowman** [comment]
> [roboticslab-uc3m/vision](https://travis-ci.org/roboticslab-uc3m/vision/builds/522246913): cannot find `libproj.so`, this is a known Xenial bug; solution: install `libproj-dev` package ([SO](https://stackoverflow.com/a/40034779))

Documented at https://github.com/roboticslab-uc3m/installation-guides/commit/e2a084520b8bbfae71a4e53ce0f835f062a53fc6.

**Comment by PeterBowman** [comment]
> [roboticslab-uc3m/openrave-yarp-plugins](https://travis-ci.org/roboticslab-uc3m/openrave-yarp-plugins/builds/522199536) (also xgnitive): "The job exceeded the maximum log length, and has been terminated." - add `-Wno-deprecated-declarations` compiler flag to reduce verbosity?

Added new `--cmake-env` option to `git-cache-dependency.sh`: https://github.com/roboticslab-uc3m/openrave-yarp-plugins/commit/6ae570b2792c9cf806192643ade1be18386d6a68. All warnings have been disabled (`-w` option).

**Comment by PeterBowman** [comment]
Now seeing narrowing issues that escalate to errors on Clang jobs, only ([ref](https://travis-ci.org/roboticslab-uc3m/openrave-yarp-plugins/jobs/522493999#L4886)):

```
/home/travis/OpenRAVE-master/plugins/ikfastsolvers/ikfastsolver.cpp:1066:49: error: 
      non-constant-expression cannot be narrowed from type 'double' to 'float'
      in initializer list [-Wc++11-narrowing]
                IkReal eetrans[3] = {t.trans.x, t.trans.y, t.trans.z};
                                                ^~~~~~~~~
/home/travis/OpenRAVE-master/plugins/ikfastsolvers/ikfastsolver.cpp:1066:49: note: 
      insert an explicit cast to silence this issue
                IkReal eetrans[3] = {t.trans.x, t.trans.y, t.trans.z};
                                                ^~~~~~~~~
                                                static_cast<float>( )
```

I need to double-check locally that the `-w` is not causing this with Clang. Might deserve an upstream patch.

**Comment by PeterBowman** [comment]
> [asrob-uc3m/yarp-devices](https://travis-ci.org/asrob-uc3m/yarp-devices/builds/522200286): `libserial-dev` should depend on `libboost-dev` since Xenial, a bug report was sent ([ref](https://bugs.launchpad.net/ubuntu/+source/libserial/+bug/1825551))

Workaround: https://github.com/asrob-uc3m/yarp-devices/commit/6b4a5ffeff673ebec78b90305145f1598d01c013. Remove that dependency and update docs ([asrob-uc3m/yarp-devices/doc/yarp-devices-install.md](https://github.com/asrob-uc3m/yarp-devices/blob/15c9d6234b741b5edc2a03edd42d1012cce4a3b8/doc/yarp-devices-install.md), https://github.com/asrob-uc3m/yarp-devices/commit/a412e453f44a36adb070c67596b74a891f3cd3f5) once [this bug](https://bugs.launchpad.net/ubuntu/+source/libserial/+bug/1825551) is solved.

**Comment by PeterBowman** [comment]
> I need to double-check locally that the `-w` is not causing this with Clang. Might deserve an upstream patch.

Solved in production branch: https://github.com/rdiankov/openrave/commit/23ad7be079086008572513fafd1f5e88da74a279. For now, set CMake option `OPENRAVE_IKFAST_FLOAT32` to `OFF` (defaults to `ON`). Traceback:

* https://github.com/rdiankov/openrave/blob/b1ebe135b4217823ebdf56d9af5fe89b29723603/plugins/ikfastsolvers/ikfastsolver.cpp#L1066-L1067 (plus line 1100)
* https://github.com/rdiankov/openrave/blob/b1ebe135b4217823ebdf56d9af5fe89b29723603/plugins/ikfastsolvers/ikfastsolver.cpp#L2419-L2430
* https://github.com/rdiankov/openrave/blob/b1ebe135b4217823ebdf56d9af5fe89b29723603/plugins/ikfastsolvers/CMakeLists.txt#L7-L9

Affects Clang 6.0 (most recent apt release on Xenial) and Clang 7.0 (current Travis Xenial images). Default Clang Xenial packaged release is 3.8, compiles successfully.
