### ISSUE TITLE
Define standard for issue labels

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/questions-and-answers#76]
Define standard for issue labels.

Additionally specify if any specific repository/project will have a different set of labels.

Personal thoughts which lead to no specific direction:
- At #57 we found out https://github.com/destan/github-label-manager is not perfect, but useful for copying issue labels
- I've been doing some priority (idea/low/high/critical) and complexity (easy/hard/tedious) labeling myself, which I think is related to scrum/agile but the main motivation is it really helps sort things out.
- At https://github.com/roboticslab-uc3m/developer-manual/blob/master/asking-questions.md ([perma](https://github.com/roboticslab-uc3m/developer-manual/blob/51d2cb68589a23fb22df86d3682ac47d1c1a00b5/asking-questions.md)) `teo-main` establishes the reference pattern. We can speak about this!
   - Maybe https://github.com/roboticslab-uc3m/project-generator/labels is a better place to put the reference pattern!
- Think if spaces should be acceptable (as well as other characters: `:`, `-`...), and alternatives if not (camelCase, etc)
- `status: in progress` is redundant wrt project column, see https://github.com/search/advanced (only issue labels), so I'd like to keep this to recommend queries such as checking WIP at [personal](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+assignee%3Ajgvictores+archived%3Afalse+label%3A%22status%3A+in+progress%22+-label%3Atracking+-label%3Aquestion+-label%3Aupstream) or [organization-wide](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+org%3Aroboticslab-uc3m+archived%3Afalse+label%3A%22status%3A+in+progress%22+-label%3Atracking+-label%3Aquestion+-label%3Aupstream) level.
- I was thinking of splitting `upstream` to describe two situations:
   1. Blocked due to factors that are external to https://github.com/roboticslab-uc3m (could be `blocked: upstream` or `upstream: blocked`, each would have corresponding color)
   2. Code broken due to upstream modifications (e.g. YARP new deprecated function, etc)

**Comment by jgvictores** [comment]
Some things commented with @David-Estevez (very related to #74)

1. We use spaces. Example: `priority: critical`
2. Remove `status: in progress` as soon as we are sure we can access kanban column info via GitHub API.
3. Under same premise as (2), remove `blocked`, rename `blocking`->`priority: blocking`
4. `regression: upstream` is simply a `regression`, we are the ones who have to fix it anyway.
5. For labels, we define the basics, but new can be added per repo.

**Comment by jgvictores** [comment]
Additional note: For handling blocked/blocking issues, it seems like the ideal solution would neither be labels nor project columns (see #74), but instead a dependency tree. :smile:

**Comment by PeterBowman** [comment]
+1 for a `regression` label.

**Comment by jgvictores** [comment]
Notes:
- https://github.com/roboticslab-uc3m/kinematics-dynamics/labels/super%20cool
- https://github.com/roboticslab-uc3m/questions-and-answers/labels/Pending%20%3Asmile%3A2%3Asmile%3A%20meeting

**Comment by jgvictores** [comment]
Lots already at https://github.com/roboticslab-uc3m/developer-manual/blob/master/best-practices-github.md#github-issues (rendered at http://robots.uc3m.es/gitbook-developer-manual/best-practices-github.html#opening-a-github-issue)

**Comment by PeterBowman** [comment]
> I was thinking of splitting `upstream` to describe two situations:

Also: broken code due to an upstream bug, found local workaround, local (RL-side) issue closed (https://github.com/roboticslab-uc3m/WBPCwaiter/issues/2#issuecomment-474417097).

**Comment by PeterBowman** [comment]
See also https://gist.github.com/Isaddo/7efebcb673a0957b9c6f07cd14826ea4 (a JS web-based label editor).

**Comment by PeterBowman** [comment]
Idea: rename *tracking* (an "issue of issues") to *horizontal* (affects multiple repos, perhaps even orgs).

**Comment by jgvictores** [comment]
> Idea: rename _tracking_ (an "issue of issues") to _horizontal_ (affects multiple repos, perhaps even orgs).

I'll begin to apply this

**Comment by PeterBowman** [comment]
See also: org-wide labels!

https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-default-labels-for-repositories-in-your-organization

**Comment by jgvictores** [comment]
> https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-default-labels-for-repositories-in-your-organization

Pretty cool. Looks like it only applies on creation of a new repo, but still very useful.

Adding [teo-main/labels](https://github.com/roboticslab-uc3m/teo-main/labels) to https://github.com/organizations/roboticslab-uc3m/settings/labels

**Comment by jgvictores** [comment]
Similar issue on `robotology` org: https://github.com/robotology/robotology.github.io/issues/10

**Comment by jgvictores** [comment]
> Adding [teo-main/labels](https://github.com/roboticslab-uc3m/teo-main/labels) to https://github.com/organizations/roboticslab-uc3m/settings/labels

Closing via :top:
