### ISSUE TITLE
Portmonitors renamed at YARP >= 3.5

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/questions-and-answers#94]
As documented at <https://github.com/robotology/yarp/pull/2552>, portmonitors were reorganized and renamed without keeping the back compatibility with the old name. A quick search shows we are affected by at least:

- [x] depthimage_to_mono (depthimage): https://github.com/search?q=org%3Aroboticslab-uc3m+depthimage&type=code
- [x] depthimage_to_rgb (depthimage2) https://github.com/search?q=org%3Aroboticslab-uc3m+depthimage2&type=code

**Comment by PeterBowman** [comment]
YARP 3.5 should be already mature enough (3.5.1 was recently released), hence it's advisable to upgrade if still using 3.4. I have replaced all occurrences except [install-yarp.md](https://github.com/roboticslab-uc3m/installation-guides/blob/566b3e75427c2c6ef72baa541930077d90193492/install-yarp.md). @jgvictores perhaps we should add a new YARP 3.5 section. Please note the `ENABLE_yarpcar_depthimage(2)` options have been renamed to `ENABLE_yarppm_depthimage_to_(mono|rgb)`.
